"""Add new link fields

Revision ID: dd1574df9655
Revises: 
Create Date: 2025-01-10 20:44:41.486754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1574df9655'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('demo_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('webapp_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=1000), nullable=True))
        batch_op.drop_column('link_type')
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=500), nullable=False))
        batch_op.add_column(sa.Column('link_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('description')
        batch_op.drop_column('webapp_url')
        batch_op.drop_column('github_url')
        batch_op.drop_column('demo_url')

    # ### end Alembic commands ###
